version: '3.8'

# Campo de extensão para evitar que o Docker tente rodar um container 'base'
x-chatwoot-base: &base
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    args:
      BUNDLE_WITHOUT: 'development:test'
      RAILS_ENV: 'production'
      RAILS_SERVE_STATIC_FILES: 'true'
  image: ${CHATWOOT_IMAGE_NAME:-rafarodrix/chatwoot:local}
  env_file: .env 
  restart: always
  networks:
    - dokploy-network

services:
  rails:
    <<: *base
    ports:
      - '0.0.0.0:${CHATWOOT_WEB_PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      - S3_PROTOCOL=${S3_PROTOCOL}
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      - S3_PROTOCOL=${S3_PROTOCOL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

networks:
  dokploy-network:
    external: true