version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: ${CHATWOOT_IMAGE_NAME:-rafarodrix/chatwoot:local}
    env_file: .env 
    restart: always

  rails:
    <<: *base
    ports:
      - '${CHATWOOT_BIND_IP:-0.0.0.0}:${CHATWOOT_WEB_PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      - S3_PROTOCOL=${S3_PROTOCOL}
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - REDIS_URL=${REDIS_URL}
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      - S3_PROTOCOL=${S3_PROTOCOL}
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  storage_data: